// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPV1HKH4o2DKrKC2IFOFifEmiHtpP8nEo',
    appId: '1:62160864857:web:502ef4ef3c338c2c529348',
    messagingSenderId: '62160864857',
    projectId: 'erickproyects',
    authDomain: 'erickproyects.firebaseapp.com',
    storageBucket: 'erickproyects.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCqIfx-wm2T1vhWn0JCeQ1H6NAL6ZRmww',
    appId: '1:62160864857:android:f3294ea2082636d8529348',
    messagingSenderId: '62160864857',
    projectId: 'erickproyects',
    storageBucket: 'erickproyects.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAENBtj6PAlCIM7_GFs167j1p2Al7pdPvo',
    appId: '1:62160864857:ios:7a2540cd31cb0f75529348',
    messagingSenderId: '62160864857',
    projectId: 'erickproyects',
    storageBucket: 'erickproyects.firebasestorage.app',
    iosBundleId: 'com.example.clase01',
  );
}
